### PR TITLE
Port to Python3

### PR DESCRIPTION
**Pull request by pratyush3124**
A task under Google Code-in.

### CODE REVIEW

**Comment by chimosky** [comment]
You should remove the spaces after the print statements as they're not important.

**Comment by Aniket21mathur** [comment]
Thanks reviewed. Looks good, please do the changes @chimosky suggested.

**Comment by pratyush3124** [comment]
Ya I deleted the extra spaces.

**Comment by quozl** [comment]
Great.  Unfinished though.  Now make it work again.  It doesn't load the SVGs.

**Comment by pratyush3124** [comment]
Could you tell me how to do it.

**Comment by chimosky** [comment]
@pratyush3124 as this is a gci task, it's your job to find out how to make it work.

**Comment by pratyush3124** [comment]
Okay I get it. But still if you have anything that could help please do tell me.

**Comment by chimosky** [comment]
One thing you can do is look at the activity log located at `~/.sugar/default/logs/activityname.log` and you should get an idea of what's wrong.

**Comment by quozl** [comment]
@pratyush3124, it has been two days and you haven't answered here about the activity log file.  I cannot imagine why you can't get a log file, as there's not enough information from you to explain that.

As an alternative practice, one which is not always reliable but is open to you for activities that do not have to join a collaboration, you can start the activity from inside the Terminal activity while inside Sugar;

* start Sugar,
* start Terminal,
* change to the directory that contains the activity; e.g.
```
cd ~/Activities/Napier.activity
```
* start the activity with the wrapper as used by Sugar; e.g.
```
sugar-activity3
```

Instead of writing to the log files, the standard error stream will be displayed on the Terminal.  The Napier activity will appear over the top of the Terminal, but you can <kbd>alt</kbd>+<kbd>tab</kbd> to switch between the Terminal and Napier.  When Napier is stopped, the shell prompt will return.

For example, on my system I've placed your branch of the Napier activity and started it in this way, and then immediately stopped it, and this is what I see;

```log
guest@guest:~$ cd /usr/share/sugar/activities/Napier.activity/
guest@guest:/usr/share/sugar/activities/Napier.activity$ sugar-activity3
/usr/share/sugar/activities/Napier.activity/NapierActivity.py:16: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GObject, GdkPixbuf
/usr/share/sugar/activities/Napier.activity/sprites.py:81: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Pango, PangoCairo
guest@guest:/usr/share/sugar/activities/Napier.activity$ █
```

Another thing is to test the activity works properly _before_ you port it, and that's in our guide to porting.

Hope that helps!

**Comment by pratyush3124** [comment]
Thanks

**Comment by quozl** [comment]
Thanks for trying!  Closing as incomplete.  If anyone would like to work on this, please do so in a new pull request, and include testing before and after.

**Comment by quozl** [comment]
https://github.com/sugarlabs/napier/pull/5

**Pull request closed without merging**
